version: '2.1'
services:
  bookstore-database:
    image: "mysql:5"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pingu123
      - MYSQL_DATABASE=bookstore
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pingu123 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  bookstore-api:
    build: .
    depends_on:
      bookstore-database:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=bookstore-database
      - DB_USER=root
      - DB_PASSWORD=pingu123
    links: 
      - "bookstore-database:bookstore-database"